### ISSUE TITLE
Detection of scripts

### ISSUE THREAD

**Issue by lfoppiano** [softcite/software-mentions#37]
Hi, in certain use cases, there is the need to detect whether a certain software or piece of application that shared, created or used within a certain article is a script or not. 

For example in a paper people may say that they share the script on which they analyzed certain data, which could be just a R, Matlab or Python script. Is this distinction extracted somewhere in softcite? 

Thank you in advance 
Luca

**Comment by kermitt2** [comment]
Hello

The extraction distinguishes environment and component (component = piece of software running in the environment), with a link from component to environment, see the [annotation schema](https://github.com/softcite/software-mentions/blob/master/doc/annotation_schema.md) and the [annotation guidelines](https://github.com/softcite/software-mentions/blob/master/doc/annotation_guidelines_tei_xml.md) for more explanations. There is a software "typing" model dedicated to this.

There is no characterization of "script" software versus "non script" software, because that's in practice too complicated to define what is a script - as it is a very ambiguous and fuzzy term in the world of software and programming.
